blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogPostSitemap
from feed import views
from comment import views
from membership import views

from django.views.static import serve
from django.conf.urls import url
sitemaps = {
    'posts':BlogPostSitemap
}

urlpatterns = [
    url(r"^sitemap\.xml/$", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("admin/", admin.site.urls),
    path("", include("feed.urls")),
    # path("<slug:slug>/", views.post_detail, name="post_detail"),
    # path("", inculde("advert.urls")),
    url(r"^accounts/", include("allauth.urls")),
    path("membership/", views.MembershipView.as_view(), name="select"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from . import views
from django.urls import path

urlpatterns = [

    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),

]

advert/models.py
from django.db import models
from sorl.thumbnail import ImageField
# Create your models here.
class Advert(models.Model):
     advert_url =  models.URLField(max_length=200,)
     title = models.CharField(max_length=200, blank=True)
     image = ImageField(upload_to='images')

comment/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Comment(models.Model):
    post = models.ForeignKey('feed.BlogPost',on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

feed/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.db import models


# Create your models here.

STATUS = ((0, "Draft"), (1, "Publish"))


class BlogPost(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.slug)])
    class Meta:
        ordering = ["-created_on"]

membership/models.py
from django.db import models
from django.conf import settings

# Create your models here.

MEMBERSHIP_CHOICES = (("pre", "Premium"), ("free", "Free"))


class Membership(models.Model):
    slug = models.SlugField(null=True, blank=True)
    membership_type = models.CharField(
        choices=MEMBERSHIP_CHOICES, default="Free", max_length=7
    )
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return self.membership_type


# this points to the user then the membership points to the defined model above


class UserMembership(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name="users_user", on_delete=models.CASCADE
    )
    membership = models.ForeignKey(
        Membership, related_name="user_membership", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.user.username


# subscrition model the boolean checks to see if the user is subbed


class Subscription(models.Model):
    user_membership = models.ForeignKey(
        UserMembership, related_name="subscription", on_delete=models.CASCADE
    )
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user_membership.user.username

comment/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

membership/forms.py
from datetime import date
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from membership.models import Membership, UserMembership, Subscription
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    free_membership = Membership.objects.get(membership_type="Free")


class Meta(UserCreationForm.Meta):
    model = user

    def save(self):
        user = super().save(commit=False)
        user.save()

        # Creating a new UserMembership
        user_membership = UserMembership.objects.create(
            user=user, membership=self.free_membership
        )
        user_membership.save()

        # Creating a new UserSubscription
        user_subscription = Subscription()
        user_subscription.user_membership = user_membership
        user_subscription.save()
        return user

advert/views.py
from django.shortcuts import render

# Create your views here.

feed/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views import generic
from advert.models import Advert
from .models import BlogPost
from comment.forms import CommentForm
from membership.models import Membership, UserMembership, Subscription
from comment.models import Comment

# Create your views here.



class PostList(generic.ListView):
    queryset = BlogPost.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"


class PostDetail(generic.DetailView):
    http_method_names = ["get", "post"]
    model = BlogPost
    template_name = "post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        context["advert"] = Advert.objects.first()
        comments_connected = Comment.objects.filter(
            post=self.get_object()
        ).order_by("created_on")
        context["comments"] = comments_connected
        
        return context
        

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect("/accounts/login/")
        else:
            return super().dispatch(request, *args, **kwargs)

    
    
    
    
    def post(self, request, *args, **kwargs):
        
        new_comment = Comment(
            body=request.POST.get("body"),
            name=request.POST.get("name"),
            post=self.get_object(),
        )
        new_comment.save()
        return self.get(self, request, *args, **kwargs)

membership/views.py
from django.shortcuts import render


from django.views.generic import ListView
from membership.models import Membership, UserMembership, Subscription

# Create your views here.


class MembershipView(ListView):
    model = Membership
    template_name = "memberships/list.html"

    def get_user_membership(self, request):
        user_membership_qs = UserMembership.objects.filter(user=self.request.user)
        if user_membership_qs.exists():
            return user_membership_qs.first()
        return None

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = self.get_user_membership(self.request)
        return context

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
<!-- style -->
<style>
    
</style>


    <!-- Navigation -->
    
  
    {%block body %}
    <!--- content --->
    {% endblock %}
    <footer class="py-3 bg-grey">
        <!-- footer items-->
        <p class="m-0 text-dark text-center ">Copyright &copy; <a href="http://MatthewSmithWebDesign.com"></a></p>
    </footer>
</body>
</html>

feed/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
   <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
   
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
     <title>{% block title%}{% endblock %}</title>
</head>

<body>

   <!-- Nav Bar-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><img id="logo" src="{% static 'img/mwswdblue-sm.jpg' %}"></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'account_login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i></a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'account_signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i></a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'account_logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                    </li>
                    
                    
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="https://www.instagram.com/matthew_webdev/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold"  href="https://twitter.com/matthew_webdev"><i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="https://github.com/MatthewSmithwebdesign"><i class="fa fa-github" aria-hidden="true"></i></a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="https://www.linkedin.com/in/matthewsmithwebdesign/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                    </li>
                
                </ul>
               
                </div>
            </div>
        </div>
    </nav>







   
<!-- Blog Content -->
    {% block content %}
    <!--- Content Here --->
   
    {% endblock content %}

    <!-- Footer Content -->

    <footer class="py-3 bg-grey">
        <!-- footer items-->
        <p class="m-0 text-dark text-center ">Copyright &copy; <a href="http://MatthewSmithWebDesign.com">Matthew Smith</p></a>
    </footer>
  </body>
</html>

feed/templates/index.html
{% extends "base.html" %} {% load static %}
{% static 'css/main.css' %}

{% block content %}


<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to a devlopers journey</h3>
                    <p class="text-light">A blog where I talk about learning to code later in life.
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Post Columns -->
        <div class="col-md-8 mt-3 left">
            {% for post in blogpost_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    <!-- advert-->
    {% if advert %}
    {{ advert.url}}
    {{ advert.image.url }}
    {% else %}
    {% endif %}
    </div>
</div>
{%endblock%}

feed/templates/memberships/list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<br>
  <h1>Choose a plan according to your needs</h1>
<hr>
<div class="row">
  {% for object in object_list %}
   <div class="col-sm-4 col-md-4">
    <div class="card" style="width: 18rem;">
<!-- <img class="card-img-top " src="{{ object.image.url }}" alt="Card image cap"> -->
      <div class="card-body">
       <h5 class="card-title">{{ object.membership_type }}</h5>
         <p class="card-text">{{ object.desc | linebreaks }}</p>
      </div>
<ul class="list-group list-group-flush">
   <li class="list-group-item"> ${{ object.price }}<small>/month</small></li>
</ul>
<div class="card-body">
     {% if object.membership_type != 'Free' %}
        <form method="POST" action="{% url 'web:select' %}">
          {% csrf_token %}
            {% if object.membership_type != current_membership %}
                <button class="btn btn-warning">Change</button>
            {% else %}
        <small>Your current plan</small>
    {% endif %}
    <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
</form>
    {% endif %}
     </div>
  </div>
 </div>
 {% endfor %}
 </div>
</div>
{% endblock content %}

feed/templates/post_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}
{% load thumbnail %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ object.author }}  {{ object.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }} <img src="{{ object.image.url }}"></p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}


    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        {% with comments.count as total_comments %}
        <h2>{{ total_comments }} Comments</h2>

        <p>
          {% endwith %} {% for comment in comments %}
        </p>

        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>

        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form id="yourform" method="POST" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {{ form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div id="advert" class="">
   <!-- advert-->
   {% if advert %}
   {% thumbnail advert.image "100x100" crop="center" as im %}
     <a href= "{{ advert.advert_url }}"class="ad">
       {{ advert.title }}
     <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a> 
   {% endthumbnail %}
   {% endif %}
</div>
{% endblock content %}

feed/templates/sidebar.html
  {% load static %} 
  
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  
  <!-- Side Bar Style -->



{% block sidebar %} 

<!-- Sidebar  -->
<div class="col-md-4 float-right ">
   <div class="card my-4">
     <h5 class="card-header">Learn about me</h5>
      <div class="card-body">
        <p class="card-text"> Hello My name is Matthew Smith. I spent 23 years as a chef and I started to learn to code in my Late 30's.
            Below you can find a link to my Portfolio site.
        </p>
          <a href="http://matthewsmithwebdesign.com"
           class="btn btn-port">My Portfolio Site</a>
           <a href='https://ko-fi.com/D1D732RX8' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi2.png?v=2' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
       </div>
    </div>
</div>

{% endblock sidebar %}